controllers:
  echo:
    strategy: RollingUpdate
    containers:
      app:
        image:
          repository: ghcr.io/mendhak/http-https-echo
          tag: 34
        env:
          HTTP_PORT: 8080
          LOG_WITHOUT_NEWLINE: true
          LOG_IGNORE_PATH: /healthz
          PROMETHEUS_ENABLED: true
        probes:
          liveness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /healthz
                port: 8080
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readiness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /healthz
                port: 8080
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
        resources:
          requests:
            cpu: 10m
          limits:
            memory: 64Mi
defaultPodOptions:
  securityContext:
    runAsNonRoot: true
    runAsUser: 65534
    runAsGroup: 65534
    seccompProfile:
      type: RuntimeDefault
service:
  app:
    controller: echo
    ports:
      http:
        port: 8080
serviceMonitor:
  app:
    serviceName: echo
    endpoints:
      - port: http
        scheme: http
        path: /metrics
        interval: 1m
        scrapeTimeout: 10s
ingress:
  app:
    className: external
    annotations:
      external-dns.alpha.kubernetes.io/target: external.zeinfahrozi.my.id
    hosts:
      - host: '{{ .Release.Name }}.zeinfahrozi.my.id'
        paths:
          - path: /
            service:
              identifier: app
              port: http
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age16t95qykfyja0lye0fnws6d5204ecj7j84ak7fx4rt43xvyusmpeq3uuxjh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6cVRlTmhtSFBtYmQ1T1hK
        ZUZVSTFaVnpxb0UvMHZKN0VWaWNLUUxtb1dZCk5LRmxwUUdXVFFtZlhtQ2dvS2hQ
        TFRYNzFMbGUxbTd2N0dTSmFmUUR0ZTgKLS0tIHJzbVZodDBmMENYVnF5em9FVHBR
        M2RNQlkrS2k1ZENJQXJwbE9rbDVjMjgKbI4Xah0qbRcT+x7xzuhqTPC2jD11GanM
        EOlH6vokSnw69Yy3CN7HU/UWKI9bGCbERu15MHoaGZtDZaP40uWPHQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-10T12:20:48Z"
  mac: ENC[AES256_GCM,data:khkorKiLKCyJ8Gizn9cDQNZvYL1yrTzeUup8TzdTy22tH3xy40rjZFX5wPFYc+ruFIivTUXKoR5azR5G/HIT+ZGVH4siNLYzaLAs/EwQCfcBj2YmoGvzTkP/zdAJl/a0mIPkxAxnIOg6rPk3Shds0s1Wo3BuZIXqT432b5Zhtnk=,iv:dtduoPjH6KkDNu2BBLMKI+JwzneGGYu4q5YAkBD3mYg=,tag:C5vLuit5eXEYs0fl5e7Jig==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
