controllers:
  echo:
    strategy: RollingUpdate
    containers:
      app:
        image:
          repository: ghcr.io/mendhak/http-https-echo
          tag: 34
        env:
          HTTP_PORT: 8080
          LOG_WITHOUT_NEWLINE: true
          LOG_IGNORE_PATH: /healthz
          PROMETHEUS_ENABLED: true
        probes:
          liveness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /healthz
                port: 8080
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readiness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /healthz
                port: 8080
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
        resources:
          requests:
            cpu: 10m
          limits:
            memory: 64Mi
defaultPodOptions:
  securityContext:
    runAsNonRoot: true
    runAsUser: 65534
    runAsGroup: 65534
    seccompProfile:
      type: RuntimeDefault
service:
  app:
    controller: echo
    ports:
      http:
        port: 8080
serviceMonitor:
  app:
    serviceName: echo
    endpoints:
      - port: http
        scheme: http
        path: /metrics
        interval: 1m
        scrapeTimeout: 10s
ingress:
  app:
    className: external
    annotations:
      external-dns.alpha.kubernetes.io/target: external.zeinfahrozi.my.id
    hosts:
      - host: '{{ .Release.Name }}.zeinfahrozi.my.id'
        paths:
          - path: /
            service:
              identifier: app
              port: http
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age16t95qykfyja0lye0fnws6d5204ecj7j84ak7fx4rt43xvyusmpeq3uuxjh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoZ0h1S3grSU5IN05KN2ZJ
        Rko5dG9lamRTS3cvWTAzK0JaNmFIV3ZPRHpjCnc5RWNtSWpURUtFRDlvc3A2aEJp
        RTVCT01BN2VZcTh0Vy91cy92NXMrUkkKLS0tIGtraGlNb3M0OXZtWjRwUno3alBy
        bEdnY1RURGZZMjRId0licktFZU5vNHcK3GhcFnzbA6Y5AciTDHv8cnL40iKp0Zoj
        ghYu/Y5xUhPkbB8pO8a7RrlAfYV3qwGXWRlYIzEtZxR51gQP8p2YjQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-09T23:59:27Z"
  mac: ENC[AES256_GCM,data:fUCgWY/hO/MQMltgxD84RH7+pIvaVMWiGKACWSXtV5bKxkweCzJKSQKSUo2nlBzSlY+EpvoQGzVmgmViiWY+9eYUPOrkrbYFRx2ViXSte+Zu/kOGaP/Ffexre4WwO4CM9516pvumj/uslu/3peAOOu7xoDop6BiJtB8eYg3gi+s=,iv:1KCkDklEH2R4FhUTV8ZOea9WcB7TAWJ+Vdz1lZdF7TA=,tag:djmeQ1BwTYGkPAFRdehh+w==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
