# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zeinfahrozi-my-id-production
spec:
  secretName: zeinfahrozi-my-id-production-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: zeinfahrozi.my.id
  dnsNames:
    - zeinfahrozi.my.id
    - '*.zeinfahrozi.my.id'
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age16t95qykfyja0lye0fnws6d5204ecj7j84ak7fx4rt43xvyusmpeq3uuxjh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvTkdFeHJoNTB3MEVJM05k
        WkNUYzU1VXZKbkhRU3ZsZGUvNnNYeHFYNkhBClZ6Nk91d3hFUGwrR1JMeEo5ZDFP
        WmdWTkg0YnVhUUFRZWJWVkFrMzE3dmcKLS0tIDVlTzQxbjZkOUhYTll0Y0V0WHpk
        U2k2dTdYekZud1pPenRUY0ZDM0YyYmMK63WuP13tBKIOAWiRUFAtoQQBjkCaS++V
        gZkv2v+h9wzaW6XsoZNZ87YHUrPKM2M2sF/ary1RetYXAgyCO195+Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-10T12:20:48Z"
  mac: ENC[AES256_GCM,data:kPQoT2AYU4i7Bwwb8oI6QqRTOU4Lk3aedsTMha1HUkWsyhqofSUMfnk8M0+w/S5K413BWsceYskCqJZ88fP3IqYnzy0cf2CW2H8yo9n6vNvmugtHwppuOVK/LSC5t/Xf/9vuWOopCDxESQXwH778lTtpalec06ZSiYbzDLp04V4=,iv:yRopEwNgGAq0ZFNIRosMTl5VySLDUP5tBBqfsS4+j0g=,tag:ef1dLqPVQ5Y75Mb9royJyQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
