# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github
  namespace: argo-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: ENC[AES256_GCM,data:87db,iv:jnhV7KZKRHfsKBs3sozL0EvJiWdVFF4a9TxxQuLITZ4=,tag:WbBPeeSRTaeOb4zfqh5w6Q==,type:str]
  url: ENC[AES256_GCM,data:OEkjdPA4v1BFff2i6bQ2+mb6rr0qvJrutY7hU/vSOrlOaIA7Eou4oz3zEjU=,iv:CvOgcPlFyivwPtrfdqPAM5O4412uG+RPakE1zT2AWcw=,tag:mIoV8NQKIcU67xKx+S34VQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age16t95qykfyja0lye0fnws6d5204ecj7j84ak7fx4rt43xvyusmpeq3uuxjh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZMHdDMlZkNnRzb1NjNjhz
        b1FnYWMxam9qb3J3ZTFzbGZpTzNmUVNVYWxnCkJ4N08wK2hHY0VVMUFDbDZsNGhz
        bEtLN0diRmZrN1JOZ29qc21UZENUSmcKLS0tIDJ5R1M3Vzl3OUJabmFWUmpvNUZU
        dUpxdFJJbUlrMldEZXFtYVBQSWRWNzQKDIgeQV/Gp22VBdhVi/XAPRb2RWUx+k0u
        /mcifhrh5qn2OJ+oiX27MI+B/1CgR1PshQ3D4eV2gOWxk4mIZmX2Zg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-10T12:20:47Z"
  mac: ENC[AES256_GCM,data:6W5mjsxDf7lOhS69FeZBZaq5CEIZMlE9dQKyR1gOhLbtwzliW7g/L69u7XCs+betD1Wng93+QYENSNvEGoMG67+qhAMZknZdQ/CNIOZx7biNxUpPnmJOmc/nuS7CvyC/cqLIdzyajJi63l71i2QN1OGvJaCp/Es2tZ1GRLHw18o=,iv:GnP9nqALqSQS69I8YeWwV8BZo8GmcbKoxblbvykM3ag=,tag:d6vckG91FaKVn0cXZYA0xg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
