# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github
  namespace: argo-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: ENC[AES256_GCM,data:Dl03,iv:CEffSG+E6Iv6x9dZyjKG+R7L7MKtsjpPCGPgS0PLd84=,tag:5dQSVHGZhFe+HB1Yj1Fpbw==,type:str]
  url: ENC[AES256_GCM,data:Zl0z4uCtFzpkq8E3f3Xg1KPvoUAx+PYUlP03OUn8bCb0bdY42N72DY1dkgQ=,iv:10nYqg+GCmH96NLgLfaOizmEt2wJySPCJ1aO7q3qNvM=,tag:sidwo4hu5JMBwDy4OGcirg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age16t95qykfyja0lye0fnws6d5204ecj7j84ak7fx4rt43xvyusmpeq3uuxjh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQbTVlY2lmOWk0ekhYaGQ1
        ZWUvenJ6R2c4aUgyVDN1M0ZSSkZnQjM2dm5ZCmNBVkcyVVhWY0dYYjZSNEtiYVdm
        TXdHZ29Ec2ZlcVZzKzdzMldDbG5vaWcKLS0tIFVSRzdpOTBWVnRDZUJOblFQTHNq
        bnk0QWp0ZTZDa3pvV0hIcmF4K3hUMXcKx49h+FJORl7XpnR4XsP16TiVJ5UQ6557
        VBmcs0n0kfuqusu3L+lltTC3MTN6ASPD7YP7h/+DnmcQ7pP3ZBbcyQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-09T23:59:27Z"
  mac: ENC[AES256_GCM,data:DUu8rPXCyjpP155wo63AZvJlkg6abeu25aaTS/FDAPfFcCHgTpHtbQXV/qqrCZdOIBAssA/ZNLrcUTaVUXo+HT3iaN/blvLzWiZtkUugGpoftyCkD0nGNFRjG8TbcxJiPkD1bvl1U2u3dAspxA2sSIHWCL8WNN3uIQ7nPjUOQB4=,iv:cuRNpclMCupZuLr/oZLNggEIFSsCW5cfRwcuiuVM9FU=,tag:DzhYzQdRWuFV0njwyBYhrQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
