apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: htmx-frontend
  namespace: argo-system
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  project: kubernetes
  source:
    repoURL: "https://https://github.com/mozarik/skripsi-monorepo.git"
    targetRevision: main
    path: microservice_example/apps/htmx_frontend
  destination:
    name: in-cluster
    namespace: default
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
