# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:7DtHkIghVWbijMoUDMtQ9BgjDMLuYiBfGO+XFOFWsg2Q2/8ORjKCYw==,iv:fefubZYXe/lg8ZvJDD/WgJsnw5PLvI3mwwMtrBSSuFQ=,tag:n8R/xIxsHYM1urSBh81knw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age16t95qykfyja0lye0fnws6d5204ecj7j84ak7fx4rt43xvyusmpeq3uuxjh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMTDg2UFRqbXY3UjBBVTRE
        NEpsNkZZNjY2bHprR1h0SDlNb0NQRWdMNTE0CmJCbGsrSDIwU09JV1dveTJJMkxp
        azBMYit3UDNQVmhOZGxhRy8vd21oT3MKLS0tIFBxL0hwTEtXV0YwT0Zyb2tnN0U4
        Tm9JOS9sRk8waEdkRlJPVDlZYWtGSW8KxlrAOcQTJxHoU0jQh6S9kfL5jDohFStC
        o1+5VbO8jRDxxI9FxvAmN+hUwh8ikWApaxerMGOcv9VsQOtZwFvODg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-10T12:20:47Z"
  mac: ENC[AES256_GCM,data:2uPAiwJAOIV9u51EgGQOWPv7yvoA6MKN0zZ5DcSZJttgRHRsTc+jOA5xZishkEjzKu/ur01pdACiBvABf2v/xKMi4mHaFUJxZObHsiQf8k69PATYtePnow9TJiSf2LeiiFymlJvFXUdkN1f13C+DqRR6XRvW+dFGWlu+h7VHgCw=,iv:hbN8y7x8LK3piOlsfFNyLvSHBkYwE6IliV6sKkSj2GA=,tag:X0hNy5jK5WXJN9qNH8v5yQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
