# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:1ET4u0CEeerydFl/W6x41Y+M57KaTqFvCSecuaNzU+/j2PsVSh6mGg==,iv:FwFuBt7Ft06l58Pg3f0BGuk2wZ7ZBPiz3KJh1XvTog4=,tag:vJgKhrZ9W3vQCOylwpS3hg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age16t95qykfyja0lye0fnws6d5204ecj7j84ak7fx4rt43xvyusmpeq3uuxjh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwVjRuT3JKeGxlQ1d0K3ZD
        cDlXVUU4MnAzYVBTaUI5NU1KQkpTMUpvM3o4CnZuZWVia3ZINTVJdHc4b0lENWp2
        TTdqNjRBR0laaFljcGNnRDVHTDFQclkKLS0tIEg2U1lMQWsyd05kME9hODZTUENW
        K0JjaDFDdG5jekFnSW1wVnZIMmEyMTQKU0V00NxPy0kvD/J4KooAc3ck1dD5LPyT
        eHz1m/5jq+bWN5qJxY7esKGbc8ZEeFZ1wou8AzepJdNAMquVoz0Dxg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-09T23:59:27Z"
  mac: ENC[AES256_GCM,data:YLpPlNqFAoWU9NLhZ8Df5mLJeV2sbkzVKl+GmTI1FeN+jeBSUkF/ymyRLgthUEek25kWTA/0AgyILR7m+1Eb9aX+iBuoWrTUDWW5OeT2GOH65pKIrtr3XaWyDYFX3PqPgYQqXzYdCp49N9lC3hn3tY3bfpTFD+AL8PJZumIfIjI=,iv:o+uuchu0L6zd7unJDDkTIoS/a7W+Oqkn9/nWcTFRsxk=,tag:LjXeM+zRO47MtXvHa9G1rA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
