fullnameOverride: k8s-gateway
domain: zeinfahrozi.my.id
ttl: 1
service:
  type: LoadBalancer
  port: 53
  annotations:
    io.cilium/lb-ipam-ips: 192.168.0.251
  externalTrafficPolicy: Cluster
watchedResources:
  - Ingress
  - Service
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age16t95qykfyja0lye0fnws6d5204ecj7j84ak7fx4rt43xvyusmpeq3uuxjh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBudVFabmNZS2N3RW1FZUs0
        dXh1aUQ1cnBJaHR1YmUyeWlLNzVvMGlORWpFCnlvYlRkRXlsNCtSc3FMSlk0M0R0
        Q0tDMlRTeTV4T2c0SDFzcm5TWnl5MG8KLS0tIG4vQ25hdTY0QnZzb3cyUjlwekpt
        TE1XLzI3WGRmSTN5S1F3WVBpcHJQQTgKR/2FWMWu8H+ZOaIx/zzxQ4CmsAXOG9iR
        ejTGQKr6JthYZmDvLtDFbf0dRT71RIWvaZgbcP/Wh34oefN7O0y4qA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-09T23:59:27Z"
  mac: ENC[AES256_GCM,data:J3n09whE2q73myrOeFoW9WBuDKcyzjmmy5JO8L83XrqHRKA38hHU9U/zHtPjAdYuvSHfTtAAI3j836yLQz3Pzbzd5FBcXnA31BxtxJ/W/XogqxmQFoQzO/EJVQtivjkIwUW8kMRmJ0N/YxGfIKtc9vX/NpOnv1FgHym3w+iTovo=,iv:0dTWSkas2caU7WLGCz2SbAaDmhAjd6xcedNHluoDE0w=,tag:gUVAHE4u+YoPZER+PnOkag==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
